name: Playwright For HW one

on:
  push:
    branches: [ GitHub-Actions-32-HW-First ]
  pull_request:
    branches: [ GitHub-Actions-32-HW-First ]

jobs:
  playwright:
    name: Run Selected Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run selected tests
        run: npx playwright test --project=selected-tests
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
