name: Playwright Tests
on:
  push:
    branches: [playwright]
  pull_request:
    branches: [playwright]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          path: html/report
          name: Main-report
        if: always()
      - name: Get report
        uses: actions/download-artifact@v3
        with:
          name: Main-report
        if: always()
